apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dfd-api
  annotations:
    haproxy.router.openshift.io/timeout: 5m
  labels:
    app: dfd
    component: api
spec:
  to:
    kind: Service
    name: dfd-api
  port:
    targetPort: proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
