apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dfd

images:
  - name: dfd
    newName: quay.io/rhopp/dfd
    newTag: latest

patches:
  - path: patches/configmap-values.yaml
