apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/namespace.yaml
  - namespace/serviceaccount.yaml
  - configmaps/dfd-config.yaml
  - configmaps/dfd-pipeline-types.yaml
  - postgresql/pvc.yaml
  - postgresql/service.yaml
  - postgresql/statefulset.yaml
  - postgresql/backup-cronjob.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/route.yaml
  - collector/deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: dfd
