apiVersion: v1
kind: Secret
metadata:
  name: dfd-database
  labels:
    app: dfd
type: Opaque
stringData:
  username: dfd
  password: CHANGE_ME
  database: dfd
  url: postgresql://dfd:CHANGE_ME@dfd-postgresql:5432/dfd
