apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dfd
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: dfd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rhopp/dfd.git
    targetRevision: main
    path: manifests/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: dfd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status
        - /spec/host
