apiVersion: v1
kind: ServiceAccount
metadata:
  name: dfd
  labels:
    app: dfd
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.dfd: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"dfd-api"}}
